const MILLISECONDS_IN_HOUR = 1000 * 60 * 60;

exports.DEFAULT_CART = { products: [], totalPrice: 0 };

// time
exports.MILLISECONDS_IN_HOUR = MILLISECONDS_IN_HOUR;
exports.MILLISECONDS_IN_DAY = MILLISECONDS_IN_HOUR * 24;
